library(data.table)
difftime <- difftime(as.POSIXct("2007-02-03"), as.POSIXct("2007-02-01"),units="mins")
rows <- as.numeric(difftime)
Pdata <- fread("household_power_consumption.txt", skip="1/2/2007", nrows = rows, header=TRUE,na.strings = c("?", ""))
setnames(Pdata, colnames(fread("household_power_consumption.txt",nrows=0)))
Pdata$DateTime <- as.POSIXct(paste(Pdata$Date, Pdata$Time), format="%d/%m/%Y %H:%M:%S")
png("plot3.png",width=480,height=480)
with(Pdata, plot(DateTime,Sub_metering_1,xlab="",ylab="",type="l"))
lines(Pdata$DateTime,Pdata$Sub_metering_2,type="l",col="Red")
lines(Pdata$DateTime,Pdata$Sub_metering_3,type="l",col="Blue")
title(main = NULL, sub = NULL, xlab = "", ylab = "Energy sub metering")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("Black","Red","Blue"),lwd=1)
dev.off()