library(data.table)
difftime <- difftime(as.POSIXct("2007-02-03"), as.POSIXct("2007-02-01"),units="mins")
rows <- as.numeric(difftime)
Pdata <- fread("household_power_consumption.txt", skip="1/2/2007", nrows = rows, header=TRUE,na.strings = c("?", ""))
setnames(Pdata, colnames(fread("household_power_consumption.txt",nrows=0)))
png("plot1.png",width=480,height=480)
hist(Pdata$Global_active_power, col='RED',main="Global Active Power",xlab="Global Active Power (kilowatts)")
dev.off()